const screens = {
  'day1': {
    id: "day1",
    back: "Screen-Day1.png",
    button: "MAKE ACME STAND OUT AS THE PREMIER FORM-LETTER MAILING SERVICE ON EARTH",
    music: "Main.mp3",
  },
  'day2': {
    id: "day2",
    back: "Screen-Day2.png",
    button: "CONTINUE WITH A FOCUS ON EXCELLENCE, CARE, AND FILLING FORMS",
    music: "Main.mp3",
  },
  'day3': {
    id: "day3",
    back: "Screen-Day3.png",
    button: "CHANGE IT UP. FOCUS ON FILLING FORMS, CARE, THEN EXCELLENCE",
    music: "Main.mp3",
  },
  'day4': {
    id: "day4",
    back: "Screen-Day4.png",
    button: "I HAVE MY CLIMBING GEAR RIGHT HERE SO LET’S SUMMIT THIS BUMP BEFORE LUNCH",
    music: "Main.mp3",
  },
  'day5': {
    id: "day5",
    back: "Screen-Day5.png",
    button: "LET'S CHURN THIS BUTTER",
    music: "Main.mp3",
  },
  'day6': {
    id: "day6",
    back: "Screen-Day6.png",
    button: "OUR COMMITMENT TO EXCELLENCE REMAINS UNAFFECTED. I WILL CONTINUE TO WORK HARD",
    music: "Main.mp3",
  },
  'day7': {
    id: "day7",
    back: "Screen-Day7.png",
    buttonl: "I WILL QUIT",
    buttonr: "I WILL CONTINUE TO WORK. MY DESK NEEDS CLEANING",
    music: "Fail.mp3",
  },
  'day8': {
    id: "day8",
    back: "Screen-Day8.png",
    buttonl: "I WILL QUIT. I NEED TO SUPPORT MY FAMILY",
    buttonr: "I WILL COME TO THE OFFICE. THINGS WILL GET BETTER",
    music: "Fail.mp3",
  },
  'day9': {
    id: "day9",
    back: "Screen-Day9.png",
    buttonl: "I WILL QUIT ANYWAYS",
    buttonr: "THIS IS GREAT NEWS. I AM READY",
    music: "Main.mp3",
  },
  'daya': {
    id: "daya",
    back: "Screen-DayA.png",
    buttonl: "I WILL QUIT",
    buttonr: "I WILL WORK",
    music: "Main.mp3",
  },
  'dayb': {
    id: "dayb",
    back: "Screen-DayB.png",
    buttonl: "I WILL QUIT",
    buttonr: "I WILL WORK",
    music: "Main.mp3",
  },
  'dayc': {
    id: "dayc",
    back: "Screen-DayC.png",
    buttonl: "I WILL QUIT",
    buttonr: "I WILL WORK ANYWAYS",
    music: "Main.mp3",
  },
  'retry': {
    id: "retry",
    back: "Screen-Retry.png",
    button: "I WILL REDEEM MYSELF IN THE EYES OF THE ACME FORM-LETTER COMPANY, AND THE WORLD",
    music: "Fail.mp3",
  },
  'fail': {
    id: "fail",
    back: "Screen-Fail.png",
    button: "YOU CAN'T FIRE ME, I QUIT",
    music: "Fail.mp3",
  },
}
